### ISSUE TITLE
关于移植pikvm

### ISSUE THREAD

**Issue by himekifee** [SwimmingTiger/oraykvm#6]
最近在研究kvm over ip，不过市面上大部分产品都是私有系统，不是很放心，而pikvm本身提供了基于linux的kvm over ip平台。且控控a2可以刷入其他内核和img，我就在想能不能直接用a2的硬件运行pikvm，有兴趣进行移植么？

**Comment by himekifee** [comment]
没事了，我问了一下，pikvm要的内存肯定比128M多。

**Comment by xe5700** [comment]
128M带点SWAP可能是可以跑的 我跑起来物理内存看起来只占了140M
